[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[functions]
  directory = "src/netlify/functions"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200